[tool.poetry]
name = "llm-filter-planning"
version = "0.1.0"
description = ""
authors = ["ZhaotingLi <zhaoting_li@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ipdb = "0.13.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
